---
- name: Download AWS-CLI
  get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/home/ubuntu/awscli-bundle.zip
  tags: aws-cli

- name: Unzip AWS-CLI
  unarchive: src=/home/ubuntu/awscli-bundle.zip dest=/home/ubuntu copy=no
  tags: aws-cli

- name: Install AWS-CLI
  shell: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
  tags: aws-cli

- name: Remove zipped installation archive
  file: path=/home/ubuntu/awscli-bundle.zip state=absent
  tags: aws-cli

- name: Remove unzipped installation archive
  command: rm -r /home/ubuntu/awscli-bundle
  tags: aws-cli
